# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lore < Formula
  desc "Agent skills package manager"
  homepage "https://github.com/pierreWagou/lore"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pierreWagou/lore/releases/download/v0.1.2/lore-darwin-amd64.tar.gz"
      sha256 "d2326afed6237c7359b467fbcb1b9ee4f337aaf6afdde888f9b585f78a5d6444"

      define_method(:install) do
        bin.install "lore"
        generate_completions_from_executable(bin/"lore", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pierreWagou/lore/releases/download/v0.1.2/lore-darwin-arm64.tar.gz"
      sha256 "1796aee062695d98e2933d297f1e14c2f5cf719db32b184868b11f17a4463d5f"

      define_method(:install) do
        bin.install "lore"
        generate_completions_from_executable(bin/"lore", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pierreWagou/lore/releases/download/v0.1.2/lore-linux-amd64.tar.gz"
      sha256 "8154145ed1a21317e8f1d35d33c60ad879d22b61ff9b3d30ffdf285fc250b789"
      define_method(:install) do
        bin.install "lore"
        generate_completions_from_executable(bin/"lore", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pierreWagou/lore/releases/download/v0.1.2/lore-linux-arm64.tar.gz"
      sha256 "20d38c0436f7305b859012493980c5ff6e1ddee489c7cf5b402163bcb7fe2f0b"
      define_method(:install) do
        bin.install "lore"
        generate_completions_from_executable(bin/"lore", "completion")
      end
    end
  end
end
