# This file was generated by GoReleaser. DO NOT EDIT.
cask "lore" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "0cf73ac96d946bb6a99d81f511bc72eb62112cfb598f59fd324eb652cd06b631"
      url "https://github.com/pierreWagou/lore/releases/download/v#{version}/lore-darwin-amd64.tar.gz",
        verified: "github.com/pierreWagou/lore"
    end
    on_arm do
      sha256 "b95d4c85a02a1efb21884db4f1bffa2a227d1d2e65fdad3f70c68292098d898b"
      url "https://github.com/pierreWagou/lore/releases/download/v#{version}/lore-darwin-arm64.tar.gz",
        verified: "github.com/pierreWagou/lore"
    end
  end

  on_linux do
    on_intel do
      sha256 "539f2577a22f47d041a18764e3816d3e7657eb408483be0e80cc125dd3a2fa1e"
      url "https://github.com/pierreWagou/lore/releases/download/v#{version}/lore-linux-amd64.tar.gz",
        verified: "github.com/pierreWagou/lore"
    end
    on_arm do
      sha256 "af909c7f24a6128fd56cba6a70c3e8799f8514cbaea956a7678b7c1100f05a04"
      url "https://github.com/pierreWagou/lore/releases/download/v#{version}/lore-linux-arm64.tar.gz",
        verified: "github.com/pierreWagou/lore"
    end
  end

  name "lore"
  desc "Agent skills package manager"
  homepage "https://github.com/pierreWagou/lore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lore"

  # No zap stanza required

end
