# This file was generated by GoReleaser. DO NOT EDIT.
cask "lore" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "f7a723b888bdab78d9537bcb88f754e88f90f22ad5774062795f2b3f34029676"
      url "https://github.com/pierreWagou/lore/releases/download/v#{version}/lore-darwin-amd64.tar.gz",
        verified: "github.com/pierreWagou/lore"
    end
    on_arm do
      sha256 "138c56655082341923f7ebdadb81a52484ed9694100e5a0abb70518d144e5f3a"
      url "https://github.com/pierreWagou/lore/releases/download/v#{version}/lore-darwin-arm64.tar.gz",
        verified: "github.com/pierreWagou/lore"
    end
  end

  on_linux do
    on_intel do
      sha256 "91b0e25008bb553288c13e778e305862dcd2820a4d0241030f7098ded6465e28"
      url "https://github.com/pierreWagou/lore/releases/download/v#{version}/lore-linux-amd64.tar.gz",
        verified: "github.com/pierreWagou/lore"
    end
    on_arm do
      sha256 "02d79d4280621f76c8e00e00df6307b1a66734f3b90c4906a14a011444773581"
      url "https://github.com/pierreWagou/lore/releases/download/v#{version}/lore-linux-arm64.tar.gz",
        verified: "github.com/pierreWagou/lore"
    end
  end

  name "lore"
  desc "Agent skills package manager"
  homepage "https://github.com/pierreWagou/lore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lore"

  # No zap stanza required

end
