# This file was generated by GoReleaser. DO NOT EDIT.
cask "lore" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "4611c18790275317fb0a41d659b65c567285b84886edb76db10d9da775a4f166"
      url "https://github.com/pierreWagou/lore/releases/download/v#{version}/lore-darwin-amd64.tar.gz",
        verified: "github.com/pierreWagou/lore"
    end
    on_arm do
      sha256 "e51c5fa36e648a79d364d6bd8533369969746d180975f05914b160f5ff120ca3"
      url "https://github.com/pierreWagou/lore/releases/download/v#{version}/lore-darwin-arm64.tar.gz",
        verified: "github.com/pierreWagou/lore"
    end
  end

  on_linux do
    on_intel do
      sha256 "5d8587547e196d53c5ffff753bb44e54c5cd31e3d0461005ce04b44b98166f7d"
      url "https://github.com/pierreWagou/lore/releases/download/v#{version}/lore-linux-amd64.tar.gz",
        verified: "github.com/pierreWagou/lore"
    end
    on_arm do
      sha256 "7402175c5cc3dc837f6c2fe32833fad4eb892754555f045759167ceb066f35c3"
      url "https://github.com/pierreWagou/lore/releases/download/v#{version}/lore-linux-arm64.tar.gz",
        verified: "github.com/pierreWagou/lore"
    end
  end

  name "lore"
  desc "Agent skills package manager"
  homepage "https://github.com/pierreWagou/lore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lore"

  # No zap stanza required

end
